# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Tokai-API-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tokai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_364d2e64e7814f26a9445137567bb970 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_390b2ce9c9214043b13a02d9015a88da }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tokai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_364d2e64e7814f26a9445137567bb970 }}/tokai/tokai-alpha-github:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Tokai-API-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9955fc8889664611b43ce1438ad9e487 }}
        images: 'tokai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_364d2e64e7814f26a9445137567bb970 }}/tokai/tokai-alpha-github:${{ github.sha }}'